name = "pvr-proxy"
main = "index.js"
compatibility_date = "2024-01-01"

[vars]
PVR_CITY = "Chennai"
PVR_LANGUAGES = "English"
PVR_GENRES = ""
PVR_CERTIFICATES = ""

[[kv_namespaces]]
binding = "KV"
id = "e2c2b8a22a46402abaf853483d4ff82f"

[triggers]
crons = ["0 6 * * *"]
